select * from goodInfo;
alter table goodinfo add BrandCode number(6);
select * from goodinfo;
select * from goodinfo order by brandcode desc;
commit;
select * from goodinfo order by name desc;
delete from goodinfo;
commit;
rollback;
select distinct name,brandcode from goodinfo;
select * from goodinfo;
select count(brandcode) from (select distinct brandcode from goodinfo);
select * from goodinfo;
select max(brandcode) brandcode from (select count(brandcode) brandcode from (select distinct brandcode from goodinfo) union (select brandcode from (select brandcode from goodinfo order by brandcode desc) where rownum=1));
select distinct name, brandcode from goodinfo;
select * from goodinfo where brandcode = 2;
select * from couponinfo;
desc couponinfo;
SELECT * FROM EMPINFO;
select * from tab;
select * from custominfo;
desc custominfo;